receivers:
  otlp:
    endpoint: 0.0.0.0:9090
exporters:
  jaeger:
    endpoint: jaeger:14250
    insecure: true
processors:
  batch:
    send_batch_size: 1
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
