receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:55680"
        cors_allowed_origins:
        - http://*
        - https://*
exporters:
  jaeger:
    endpoint: jaeger:14250
    insecure: true
processors:
  batch:
    send_batch_size: 1
extensions:
  zpages:
    endpoint: "0.0.0.0:55679"
service:
  extensions : [zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
