services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    networks:
      - otelcol
    ports:
      - "16686:16686"
      - "4317"
  zipkin:
    image: openzipkin/zipkin-slim:latest
    networks:
      - otelcol
    ports:
      - "9411:9411"
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.115.1
    networks:
      - otelcol
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4318"
      - "55679:55679"
    depends_on:
      - jaeger

networks:
  otelcol:
